import {
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiReact,
  SiAngular,
  SiVuedotjs,
  SiSvelte,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiPostgresql,
  SiFirebase,
  SiAmazon,
  SiGooglecloud,
  SiDocker,
  SiKubernetes,
  SiGit,
  SiGithub,
  SiJenkins,
  SiTerraform,
  SiPython,
  SiNextdotjs,
  SiTailwindcss,
  SiFigma,
} from "react-icons/si";
import { BsMicrosoft } from "react-icons/bs";

export const icons = [
  { id: "html", icon: SiHtml5, color: "#E34F26" },
  { id: "css", icon: SiCss3, color: "#1572B6" },
  { id: "javascript", icon: SiJavascript, color: "#F7DF1E" },
  { id: "typescript", icon: SiTypescript, color: "#3178C6" },
  { id: "react", icon: SiReact, color: "#61DAFB" },
  { id: "angular", icon: SiAngular, color: "#DD0031" },
  { id: "vue", icon: SiVuedotjs, color: "#4FC08D" },
  { id: "svelte", icon: SiSvelte, color: "#FF3E00" },
  { id: "nodejs", icon: SiNodedotjs, color: "#339933" },
  { id: "express", icon: SiExpress, color: "#000000" },
  { id: "mongodb", icon: SiMongodb, color: "#47A248" },
  { id: "postgresql", icon: SiPostgresql, color: "#4169E1" },
  { id: "firebase", icon: SiFirebase, color: "#FFCA28" },
  { id: "aws", icon: SiAmazon, color: "#232F3E" },
  { id: "azure", icon: BsMicrosoft, color: "#0078D4" },
  { id: "gcp", icon: SiGooglecloud, color: "#4285F4" },
  { id: "docker", icon: SiDocker, color: "#2496ED" },
  { id: "kubernetes", icon: SiKubernetes, color: "#326CE5" },
  { id: "git", icon: SiGit, color: "#F05032" },
  { id: "github", icon: SiGithub, color: "#181717" },
  { id: "jenkins", icon: SiJenkins, color: "#D24939" },
  { id: "terraform", icon: SiTerraform, color: "#7B42BC" },
  { id: "python", icon: SiPython, color: "#3776AB" },
  { id: "nextjs", icon: SiNextdotjs, color: "#000000" },
  { id: "tailwind", icon: SiTailwindcss, color: "#06B6D4" },
  { id: "figma", icon: SiFigma, color: "#F24E1E" },
]; 